repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml #Attempts to load all yaml files to verify syntax.
    -   id: check-json #Attempts to load all json files to verify syntax.
    -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
    -   id: name-tests-test #verifies that test files are named correctly.
    -   id: check-merge-conflict # Check for files that contain merge conflict strings.
    -   id: check-toml # Attempts to load all TOML files to verify syntax.
    -   id: check-docstring-first #Checks for a common error of placing code before the docstring.
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

